public enum COLD_COFFEES {


}

enum COLD_BREWS {

    IRISH_CREAM_COLD_BREW,
    SALTED_CARAMEL_CREAM_COLD_BREW,
    STARBUCKS_RESERVE_COLD_BREW,
    STARBUCKS_COLD_BREW_COFFEE,
    VANILLA_SWEET_CREAM_COLD_BREW,
    STARBUCKS_COLD_BREW_COFFEE_WITH_MILK,
}

enum NITRO_COLD_BREWS {

    STARBUCKS_RESERVE_NITRO_COLD_BREW,
    NITRO_COLD_BREW,
    VANILLA_SWEET_CREAM_NITRO_COLD_BREW,
}

enum ICED_AMERICANO {

    ICED_CAFFE_AMERICANO,
}

enum ICED_COFFEES {

    ICED_COFFEE,
    ICED_COFFEE_WITH_MILK,
    ICED_ESPRESSO,
}

enum ICED_SHAKEN_ESPRESSO {

    ICED_BROWN_SUGAR_OATMILK_SHAKEN_ESPRESSO,
    ICED_BROWN_SUGAR_ALMONDMILK_SHAKEN_ESPRESSO,
    ICED_SHAKEN_ESPRESSO,
}

enum ICED_FLAT_WHITES {

    ICED_FLAT_WHITE,
    ICED_HONEY_ALMONDMILK_FLAT_WHITE,
}

enum ICED_LATTES {

    ICED_PISTACHIO_LATTE,
    ICED_SUGAR_COOKIE_ALMONDMILK_LATTE,
    ICED_CHESTNUT_PRALINE_LATTE,
    ICED_CARAMEL_BRULEE_LATTE,
    STARBUCKS_RESERVE_ICED_LATTE,
    STARBUCKS_RESERVE_ICED_HAZELNUT_BIANCO_LATTE,
    ICED_CAFFE_LATTE,
    ICED_CINNAMON_DOLCE_LATTE,
    ICED_STARBUCKS_BLONDE_VANILLA_LATTE,
}

enum ICED_MACCHIATOS {

    ICED_CARAMEL_MACCHIATO,
}

enum ICED_MOCHAS {

    ICED_WHITE_CHOCOLATE_MOCHA,
    ICED_PEPPERMINT_WHITE_CHOCOLATE_MOCHA,
    ICED_TOASTED_WHITE_CHOCOLATE_MOCHA,
    ICED_PEPPERMINT_MOCHA,
    ICED_CAFFE_MOCHA,
    STARBUCKS_RESERVE_ICED_DARK_CHOCOLATE_MOCHA,
}

enum ICED_CLOVER_BREWED_COFFEES {

    ICED_JAMAICA_BLUE_MOUNTAIN_CLOVER_STARBUCKS_RESERVE,
    ICED_SUNDRIED_ETHIOPIA_GERA_FARM_CLOVER_STARBUCKS_RESERVE,
    ICED_CLOVER_STARBUCKS_RESERVE_GUATEMALA_SANTA_CLARA_ESTATE,
    ICED_VIETNAM_DA_LAT_CLOVER_STARBUCKS_RESERVE,
    ICED_COSTA_RICA_NARANJO_CLOVER_STARBUCKS_RESERVE,
    ICED_HAWAII_KAU_CLOVER_STARBUCKS_RESERVE,
    ICED_ICED_CLOVER_BREWED_PIKE_PLACE_ROAST,
    ICED_ORGANIC_YUKON_BLEND_CLOVER,
    ICED_CLOVER_BREWED_GOLD_COAST_BLEND,
    ICED_CLOVER_BREWED_BREAKFAST_BLEND,
    ICED_KENYA_CLOVER,
    ICED_VERANDA_BLEND_CLOVER,
    ICED_CLOVER_BREWED_STARBUCKS_WILLOW_BLEND,
    ICED_DECAF_SUMATRA_CLOVER,
    ICED_CAFFE_VERONA_CLOVER,
    ICED_CLOVER_BREWED_DECAF_PIKE_PLACE_ROAST,
    ICED_ESPRESSO_ROAST_CLOVER,
    ICED_DECAF_ESPRESSO_ROAST_CLOVER,
    ICED_ETHIOPIA_CLOVER,
    ICED_FRENCH_ROAST_CLOVER,
    ICED_ITALIAN_ROAST_CLOVER,
    ICED_KOMODO_DRAGON_CLOVER,
    ICED_SUMATRA_CLOVER,
}