public enum COLD_COFFEES {


}

enum COLD_BREWS {

    IRISH_CREAM_COLD_BREW,
    SALTED_CARAMEL_CREAM_COLD_BREW,
    STARBUCKS_RESERVE_COLD_BREW,
    STARBUCKS_COLD_BREW_COFFEE,
    VANILLA_SWEET_CREAM_COLD_BREW,
    STARBUCKS_COLD_BREW_COFFEE_WITH_MILK,
}

enum NITRO_COLD_BREWS {

    STARBUCKS_RESERVE_NITRO_COLD_BREW,
    NITRO_COLD_BREW,
    VANILLA_SWEET_CREAM_NITRO_COLD_BREW,
}

enum ICED_AMERICANO {

    ICED_CAFFE_AMERICANO,
}

enum ICED_COFFEES {

    ICED_COFFEE,
    ICED_COFFEE_WITH_MILK,
    ICED_ESPRESSO,
}

enum ICED_SHAKEN_ESPRESSO {

    ICED_BROWN_SUGAR_OATMILK_SHAKEN_ESPRESSO,
    ICED_BROWN_SUGAR_ALMONDMILK_SHAKEN_ESPRESSO,
    ICED_SHAKEN_ESPRESSO,
}

enum ICED_FLAT_WHITES {

    ICED_FLAT_WHITE,
    ICED_HONEY_ALMONDMILK_FLAT_WHITE,
}

enum ICED_LATTES {

    ICED_PISTACHIO_LATTE,
    ICED_SUGAR_COOKIE_ALMONDMILK_LATTE,
    ICED_CHESTNUT_PRALINE_LATTE,
    ICED_CARAMEL_BRULEE_LATTE,
    STARBUCKS_RESERVE_ICED_LATTE,
    STARBUCKS_RESERVE_ICED_HAZELNUT_BIANCO_LATTE,
    ICED_CAFFE_LATTE,
    ICED_CINNAMON_DOLCE_LATTE,
    ICED_STARBUCKS_BLONDE_VANILLA_LATTE,
}

enum ICED_MACCHIATOS {

    ICED_CARAMEL_MACCHIATO,
}