public enum COLD_COFFEES {


}

enum COLD_BREWS {

    IRISH_CREAM_COLD_BREW,
    SALTED_CARAMEL_CREAM_COLD_BREW,
    STARBUCKS_RESERVE_COLD_BREW,
    STARBUCKS_COLD_BREW_COFFEE,
    VANILLA_SWEET_CREAM_COLD_BREW,
    STARBUCKS_COLD_BREW_COFFEE_WITH_MILK,
}

enum NITRO_COLD_BREWS {

    STARBUCKS_RESERVE_NITRO_COLD_BREW,
    NITRO_COLD_BREW,
    VANILLA_SWEET_CREAM_NITRO_COLD_BREW,
}

enum ICED_AMERICANO {

    ICED_CAFFE_AMERICANO,
}

enum ICED_COFFEES {

    ICED_COFFEE,
    ICED_COFFEE_WITH_MILK,
    ICED_ESPRESSO,
}

enum ICED_SHAKEN_ESPRESSO {

}