public enum general {


}

enum AMERICANOS {

    CAFFE_AMERICANO,
}

enum BREWED_COFFEES {

    VERANDA_BLEND,
    CAFFE_MISTO,
    FEATURED_STARBUCKS_DARK_ROAST_COFFEE,
    PIKE_PLACE_ROAST,
    DECAF_PIKE_PLACE_ROAST,
}

enum CAPPUCCINOS {

    CAPPUCCINO,
}

enum ESPRESSO_SHOTS {

    ESPRESSO,
    ESPRESSO_CON_PANNA,
}

enum FLAT_WHITES {

    FLAT_WHITE,
    HONEY_ALMONDMILK_FLAT_WHITE,
}

enum LATTES {

    PISTACHIO_LATTE,
    SUGAR_COOKIE_ALMONDMILK_LATTE,
    CHESTNUT_PRALINE_LATTE,
    CARAMEL_BRULEE_LATTE,
    CAFFE_LATTE,
    CINNAMON_DOLCE_LATTE,
    STARBUCKS_RESERVE_LATTE,
    STARBUCKS_RESERVE_HAZELNUT_BIANCO_LATTE,
    STARBUCKS_BLONDE_VANILLA_LATTE,
}

enum MACCHIATOS {

    CARAMEL_MACCHIATO,
    ESPRESSO_MACCHIATO,
}

enum MOCHAS {

    TOASTED_WHITE_CHOCOLATE_MOCHA,
    PEPPERMINT_WHITE_CHOCOLATE_MOCHA,
    PEPPERMINT_MOCHA,
    CAFFE_MOCHA,
    STARBUCKS_RESERVE_DARK_CHOCOLATE_MOCHA,
    WHITE_CHOCOLATE_MOCHA,;


}

