public enum HOT_DRINKS {

}

enum HOT_CHOCOLATES {

    TOASTED_WHITE_HOT_CHOCOLATE,
    PEPPERMINT_WHITE_HOT_CHOCOLATE,
    PEPPERMINT_HOT_CHOCOLATE,
    HOT_CHOCOLATE,
    WHITE_HOT_CHOCOLATE,
}

enum HOT_JUICE {

    CARAMEL_APPLE_SPICE,
    STEAMED_APPLE_JUICE,
}

enum STEAMERS {

    PISTACHIO_CREME,
    CHESTNUT_PRALINE_CREME,
    CARMEL_BRULEE_CREME,
    CINNAMON_DOLCE_CREME,
    STEAMED_MILK,
    VANILLA_CREME,
}