public enum HOT_COFFEES {


}

enum AMERICANOS {

    CAFFE_AMERICANO,
}

enum BREWED_COFFEES {

    VERANDA_BLEND,
    CAFFE_MISTO,
    FEATURED_STARBUCKS_DARK_ROAST_COFFEE,
    PIKE_PLACE_ROAST,
    DECAF_PIKE_PLACE_ROAST,
}

enum CAPPUCCINOS {

    CAPPUCCINO,
}

enum ESPRESSO_SHOTS {

    ESPRESSO,
    ESPRESSO_CON_PANNA,
}

enum FLAT_WHITES {

    FLAT_WHITE,
    HONEY_ALMONDMILK_FLAT_WHITE,
}

enum LATTES {

    PISTACHIO_LATTE,
    SUGAR_COOKIE_ALMONDMILK_LATTE,
    CHESTNUT_PRALINE_LATTE,
    CARAMEL_BRULEE_LATTE,
    CAFFE_LATTE,
    CINNAMON_DOLCE_LATTE,
    STARBUCKS_RESERVE_LATTE,
    STARBUCKS_RESERVE_HAZELNUT_BIANCO_LATTE,
    STARBUCKS_BLONDE_VANILLA_LATTE,
}

enum MACCHIATOS {

    CARAMEL_MACCHIATO,
    ESPRESSO_MACCHIATO,
}

enum MOCHAS {

    TOASTED_WHITE_CHOCOLATE_MOCHA,
    PEPPERMINT_WHITE_CHOCOLATE_MOCHA,
    PEPPERMINT_MOCHA,
    CAFFE_MOCHA,
    STARBUCKS_RESERVE_DARK_CHOCOLATE_MOCHA,
    WHITE_CHOCOLATE_MOCHA,;
}

enum CLOVER_BREWED_COFFEES {

    JAMAICA_BLUE_MOUNTAIN_CLOVER_STARBUCKS_RESERVE,
    SUNDRIED_ETHIOPIA_GERA_FARM_CLOVER_STARBUCKS_RESERVE,
    CLOVER_STARBUCKS_RESERVE_GUATEMALA_SANTA_CLARA_ESTATE,
    VIETNAM_DA_LAT_CLOVER_STARBUCKS_RESERVE,
    COSTA_RICA_NARANJO_CLOVER_STARBUCKS_RESERVE,
    HAWAII_KAU_CLOVER_STARBUCKS_RESERVE,
    CLOVER_BREWED_PIKE_PLACE_ROAST,
    ORGANIC_YUKON_BLEND_CLOVER,
    CLOVER_BREWED_GOLD_COAST_BLEND,
    CLOVER_BREWED_BREAKFAST_BLEND,
    KENYA_CLOVER,
    VERANDA_BLEND_CLOVER,
    CLOVER_BREWED_STARBUCKS_WILLOW_BLEND,
    DECAF_SUMATRA_CLOVER,
    CAFFE_VERONA_CLOVER,
    CLOVER_BREWED_DECAF_PIKE_PLACE_ROAST,
    ESPRESSO_ROAST_CLOVER,
    DECAF_ESPRESSO_ROAST_CLOVER,
    ETHIOPIA_CLOVER,
    FRENCH_ROAST_CLOVER,
    ITALIAN_ROAST_CLOVER,
    KOMODO_DRAGON_CLOVER,
    SUMATRA_CLOVER,
}

enum COFFEE_TRAVELERS {

    COFFEE_TRAVELER_VERANDA_BLEND,
    COFFEE_TRAVELER_DARK_ROAST,
    COFFEE_TRAVELER_PIKE_PLACE_ROAST,
    COFFEE_TRAVELER_DECAF_PIKE_PLACE_ROAST,
}