public enum ICED_TEAS {


}

enum BOTTLED_TEAS {

    TEAVANA_SPARKLING_UNSWEETENED_PEACH_NECTARINE_GREEN_TEA,
    TEAVANA_MANGO_BLACK_TEA,
}

enum ICED_BLACK_TEAS {

    ICED_BLACK_TEA,
    ICED_BLACK_TEA_LEMONADE,
    ICED_ROYAL_ENGLISH_BREAKFAST_TEA_LATTE,
    ICED_LONDON_FOG_TEA_LATTE,
}

enum ICED_CHAI_TEAS {

    ICED_CHAI_TEA_LATTE,
}

enum ICED_GREEN_TEAS {

    ICED_PEACH_GREEN_TEA,
    ICED_PEACH_GREEN_TEA_LEMONADE,
    ICED_MATCHA_TEA_LATTE,
    ICED_GREEN_TEA,
    ICED_GREEN_TEA_LEMONADE,
    ICED_MATCHA_LEMONADE,
}

enum ICED_HERBAL_TEAS {

    ICED_PASSION_TANGO_TEA,
    ICED_PASSION_TANGO_TEA_LEMONADE,
}